// Importing Inter font from the next/font/google module
import { Inter } from "next/font/google";
// Importing global styles from the globals.css file
import "./globals.css";
// Importing Navbar component from the Navbar.js file
import Navbar from "./components/Navbar";

// Creating a new instance of Inter font with specified subsets
const inter = Inter({ subsets: ["latin"] });

// Metadata for the application
export const metadata = {
  title: "To-DO-Next APP",
  description: "Generated by create next app",
};

// Functional component RootLayout representing the root layout of the application
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Setting the body font family to Inter */}
      <body className={inter.className}>
        {/* Rendering the Navbar component */}
        <Navbar/>
        {/* Rendering the children components */}
        {children}
      </body>
    </html>
  );
}
